
CORRECT_ANSWER = 'Y'
INCORRECT_ANSWER = 'N'
UNDECIDED_ANSWER = 'U'

# object types
EQUATIONS = 0
HANDWRITTEN = 1

# variables in a bounding box
X = 0
Y = 1
W = 2
H = 3

DEFAULT_SYMBOL_WIDTH = 160

TEST_DATA_ANNOTATIONS_PATH = 'evaluation_data/test_annotations/'
TEST_DATA_BOX_ANNOTATIONS_PATH = 'evaluation_data/test_annotations/000/'
TEST_DATA_PATH = 'evaluation_data/test_images/'


OUTPUT_PATH = 'output/'

NUMBER_OF_IMAGE_TYPES = 5
NUMBER_OF_IMAGES = 20
NUMBER_IMAGES_PODTYPES = 2

DEBUG_ONE_FILE = False
DEBUG_FILENAME = '2_1_1'
DEBUG_WITHOUT_PREDICTIONS = False

# file extensions
JPG = '.jpg'
TXT = '.txt'

# model variables
LABELS_PATH = 'model/obj.names'
CONFIG_PATH = 'model/yolov3.cfg'
WEIGHTS_PATH = 'model/yolov3.weights'

CONFIDENCE = 0.1
THRESHOLD = 0.05

SAME_LINE_CHARACTER_SPACE = 100

BOX = 0
PREDICTION = 1
CLASS_ID = 2
IS_LEGITIMATE = 3

POSSIBLE_OVERLAP_WIDTH = 50
POSSIBLE_WIDTH_BETWEEN_CLOSE_OBJECTS = 100

# application modes
EVALUATIONAL_MODE = 0
SIMPLE_MODE = 1
DETAILED_MODE = 2
VIDEO_MODE = 3

SUCCESS_PERCENT = 0.5

SMILE = 0
NEUTRAL = 1
SAD = 2

EMOTION_PATH = 'images/emotions/'
SMILE_PATH = EMOTION_PATH + 'happy.png'
NEUTRAL_PATH = EMOTION_PATH + 'neutral.png'
SAD_PATH = EMOTION_PATH + 'sad.png'

REACTION_PATH = 'images/reactions/'
RIGHT_IMG_PATH = REACTION_PATH + 'right.png'
WRONG_IMG_PATH = REACTION_PATH + 'wrong.png'

CORNER_PATH = 'images/corner/'
STAR_CORNER_IMG_PATH = CORNER_PATH + 'star.png'
LINES_CORNER_IMG_PATH = CORNER_PATH + 'lines.png'

CORNER_IMAGE_PATH = LINES_CORNER_IMG_PATH

DEFAULT_PROGRAM_IMGS_PATH = 'images/program_images/'

WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 750

DEFAULT_IMG_NAME = 'capture'


EXPRESSIONS_LBL = 0
TEXT_RESULTS_LBL = 1
FINAL_TEXT_LBL = 2

# equation detection
DEFAULT_SYMBOL_WIDTH_EQUATIONS = 80
LEFT = 0
RIGHT = 1
BOTH = 2
SYMBOL_WIDTH_MULTIPLIER = 1
ACCEPTABLE_LOOP_NUMBER = 1

# handwritten digit detection
INCREASE_BORDER_VALUE = 12

INCREASE_HANDWRITTEN_BORDER_VALUE = 20
MAX_ACCEPTABLE_BLACK_PIXEL_COUNT = 6
MAX_BLACK_VALUE = 120
MIN_WHITE_VALUE = 20

DIGIT_IMAGE_SIZE = 28
